default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development: &development
  <<: *default
  database: digging_stock_development
  host: 127.0.0.1
  username: root
  password:

test:
  <<: *development
  database: <%= "digging_stock_test#{ENV['TEST_ENV_NUMBER']}" %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'kakastock_production' %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
